server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;


    location = / {
        return 302 /fr/;
    }


    location ~ ^/(fr|en-US)/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /$1/index.html;
    }

    error_page 404 = /fr/index.html;
}